### ISSUE TITLE
Error after upgrade HA to 2023.3

### ISSUE THREAD

**Issue by adolfomendes** [lewei50/ha_iammeter_modbus#3]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 08:09:37 (1 occurrences)
Last logged: 08:09:37

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for irrigationprogram using this method at custom_components/irrigationprogram/__init__.py, line 32: hass.config_entries.async_setup_platforms(entry, (Platform.SWITCH,))

**Comment by celeduc** [comment]
Error occurred loading configuration flow for integration iammeter_modbus: No module named 'pymodbus.client.sync'
9:21:38 PM – (ERROR) config_entries.py
Setup failed for custom integration iammeter_modbus: Unable to import component: No module named 'pymodbus.client.sync'
9:20:46 PM – (ERROR) setup.py

**Comment by schwarzelise** [comment]
patch worked for me!

**Comment by adolfomendes** [comment]
Solved
