### ISSUE TITLE
After update V1.07 iammeter doesnt work

### ISSUE THREAD

**Issue by zsgodor** [lewei50/ha_iammeter_modbus#4]
Hi,
I upgraded V1.07, after reboot i received this error.:
My iammeter  iammeter W3080T 3 phase meter.
Firmware Ver.: | ATVi.75.98.1@MX1290

Logger: homeassistant
Source: custom_components/iammeter_modbus/__init__.py:189
Integration: IamMeter Modbus (documentation, issues)
First occurred: du. 3:21:28 (4 occurrences)
Last logged: du. 3:25:24

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/iammeter_modbus/__init__.py", line 143, in async_refresh_modbus_data
    update_result = self.read_modbus_data()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iammeter_modbus/__init__.py", line 173, in read_modbus_data
    return self.read_modbus_holding_registers()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iammeter_modbus/__init__.py", line 189, in read_modbus_holding_registers
    inverter_data.registers, byteorder=Endian.BIG
                                       ^^^^^^^^^^
AttributeError: type object 'Endian' has no attribute 'BIG'
![Képernyőfotó 2023-09-12 - du  3 30 04](https://github.com/lewei50/ha_iammeter_modbus/assets/64435192/37ee496f-f7ed-4238-bcc9-bd466332ad52)

I deleted, re add, the integration not helped, i rebooted my W3080T but cant help me.
My operation system is Debian 11, HA in docker, HA version 2023.9.1

I downgrade v1.06,v1.05 but cant work again.
Can you help me please solve this problem?
Thank You Zsolt

**Comment by zsgodor** [comment]
Here is the solution, BUT I don't dare to update, v1.07
1, Remove the integration from HA
2, Remove the integration from HACS
3, Reboot HA.
4, Install integration in HACS
5, Add integration HA.
7, = WORK AGAIN this version v1.0.6
I don't know upgrade v1.0.7 or not.

**Comment by yangbo1979** [comment]
because "requirements": ["pymodbus"] version is lower than needed,should fix in next iammeter_mobus release.
or change it in file manifest.json:
"requirements": ["pymodbus>=3.6.6"]

**Comment by yangbo1979** [comment]
fixed in released version 1.0.10.
