### ISSUE TITLE
System slow down when ammeter is not reachable

### ISSUE THREAD

**Issue by klugev303** [lewei50/ha_iammeter_modbus#5]
A problem occurs, after disconnecting, the power is turned off (I have one device connected to the generator, and it works)
and the ammeter becomes unavailable on the network. Home Assistant correctly reports the problem in the logs and sensor 
records are unavailable as expected.

However, the entire **home assistant becomes unresponsive. Pages are rendering with a huge timeout and some widgets
(not related to iammeter)** are reporting problems. Returning to iammeter_http or powering up the device eventually
solves all problems.

Modbus communication seems to be blocking other operations.

**Comment by relioti** [comment]
Try my fork https://github.com/relioti/ha_iammeter_modbus

**Comment by ProdanAS** [comment]
True that, it brings mu home assistant to its knees. This is very Bad

**Comment by yangbo1979** [comment]
try to fix it in next iammber_modbus release.

**Comment by yangbo1979** [comment]
try released version 1.0.10.
