### ISSUE TITLE
After the last update, Iam stopped working

### ISSUE THREAD

**Issue by Mazurekmazi** [lewei50/ha_iammeter_modbus#9]
Hello, after the last update, Iam stopped working and when I try to configure it, only a message appears: {"message":"Invalid handler specified"}

**Comment by ringhio80** [comment]
just reverted back to v1.0.12 and started back working....

**Comment by yangbo1979** [comment]
Thanks for your feedback,this error was fixed in v1.0.14.
Should using "space" instead of "tab" in code format.
